# Generated by Django 4.2.20 on 2025-04-23 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_start_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(default=None, null=True)),
                ('courier', models.CharField(blank=True, choices=[('fedex', 'FedEx'), ('dhl', 'DHL'), ('ups', 'UPS'), ('usps', 'USPS'), ('ems', 'EMS')], default=None, max_length=10)),
                ('tracking_number', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.IntegerField()),
                ('isVerified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InProgressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('name', models.CharField(default='', max_length=20, null=True)),
                ('phone', models.CharField(default='', max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inprogress_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, default=None, max_length=12)),
                ('order_created_at', models.DateTimeField()),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('last_address', models.TextField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_item_url', models.URLField(blank=True, null=True)),
                ('stripe_item_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_delivery_url', models.URLField(blank=True, null=True)),
                ('stripe_delivery_id', models.CharField(blank=True, max_length=200, null=True)),
                ('item_is_paid', models.BooleanField(default=False)),
                ('delivery_is_paid', models.BooleanField(default=False)),
                ('item_invoice_created_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_invoice_created_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='usrinfo.inprogressorder')),
            ],
        ),
        migrations.CreateModel(
            name='PastOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_items', to='usrinfo.pastorder')),
            ],
        ),
        migrations.CreateModel(
            name='InProgressOrderSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_received', models.BooleanField(default=False)),
                ('item_fee_paid', models.BooleanField(default=False)),
                ('item_purchased', models.BooleanField(default=False)),
                ('delivery_ready', models.BooleanField(default=False)),
                ('delivery_fee_paid', models.BooleanField(default=False)),
                ('delivery_started', models.BooleanField(default=False)),
                ('delivery_completed', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='usrinfo.inprogressorder')),
            ],
        ),
        migrations.CreateModel(
            name='InProgressOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('gpt_product_name', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usrinfo.inprogressorder')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='usrinfo.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='usrinfo.inprogressorder'),
        ),
    ]
