# Generated by Django 5.2 on 2025-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='community_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
