# Generated by Django 4.2.20 on 2025-04-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='inprogressorderitem',
            name='gpt_product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
