# Generated by Django 4.2.20 on 2025-04-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0002_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_image_url', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='usrinfo.profile')),
            ],
        ),
    ]
