# Generated by Django 4.2.20 on 2025-04-01 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usrinfo', '0002_emailverification_rename_username_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_start_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(default=None, null=True)),
                ('courier', models.CharField(default=None, max_length=10)),
                ('tracking_number', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InProgressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inprogress_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InProgressOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usrinfo.inprogressorder')),
            ],
        ),
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, default=None, max_length=12)),
                ('order_created_at', models.DateTimeField()),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_items', to='usrinfo.pastorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='submittedorder',
            name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='did_pay',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='RealOrder',
        ),
        migrations.DeleteModel(
            name='SubmittedOrder',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='usrinfo.inprogressorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='usrinfo.inprogressorder'),
        ),
    ]
