# Generated by Django 5.2 on 2025-05-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0003_alter_profile_community_address_postlikes_userlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='liked_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes_users', to='usrinfo.profile'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='usrinfo.post'),
        ),
    ]
