# Generated by Django 4.2.20 on 2025-04-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0004_alter_payment_delivery_fee_alter_payment_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressOrderSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_received', models.BooleanField(default=False)),
                ('item_purchased', models.BooleanField(default=False)),
                ('item_received', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('delivery_started', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='usrinfo.inprogressorder')),
            ],
        ),
    ]
