# Generated by Django 4.2.20 on 2025-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0005_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
