# Generated by Django 4.2.20 on 2025-04-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0005_inprogressordersteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inprogressordersteps',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='usrinfo.inprogressorder'),
        ),
    ]
