# Generated by Django 4.2.20 on 2025-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0006_post_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
