# Generated by Django 4.2.20 on 2025-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0007_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
