# Generated by Django 4.2.20 on 2025-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0008_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar_image_url',
            field=models.URLField(blank=True, default='https://bidangilimage.s3.us-west-1.amazonaws.com/profiles/basic_avatar.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, default='https://bidangilimage.s3.us-west-1.amazonaws.com/profiles/basic_avatar.png'),
        ),
    ]
