# Generated by Django 5.2 on 2025-05-21 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0008_alter_postcomment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnet_like', to='usrinfo.postcomment')),
                ('liked_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes_users', to='usrinfo.profile')),
            ],
        ),
    ]
