# Generated by Django 4.2.20 on 2025-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrinfo', '0009_post_avatar_alter_avatar_avatar_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.URLField(blank=True, default='https://bidangilimage.s3.us-west-1.amazonaws.com/profiles/basic_avatar.png'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
